# Generated by Django 5.2.11 on 2026-02-07 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0006_agency_currency_agency_fuel_fee_default_and_more'),
        ('clients', '0002_client_delete_clientuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('closed', 'Clôturé')], default='draft', max_length=20)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('km_depart', models.PositiveIntegerField(default=0)),
                ('km_retour', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_depart', models.PositiveSmallIntegerField(default=8, help_text='1-8 gauge')),
                ('fuel_retour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('km_included', models.PositiveIntegerField(default=200)),
                ('km_price', models.DecimalField(decimal_places=2, default=0.3, max_digits=6)),
                ('fuel_fee', models.DecimalField(decimal_places=2, default=30.0, max_digits=8)),
                ('late_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('currency', models.CharField(default='EUR', max_length=5)),
                ('frais_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_carburant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_degats', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('frais_retard', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Impayé'), ('partial', 'Partiel'), ('paid', 'Payé')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='agencies.agency')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.client')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='agencies.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=5)),
                ('provider', models.CharField(default='manual', max_length=20)),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('card_terminal', 'Terminal CB'), ('bank_transfer', 'Virement')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('succeeded', 'Réussi'), ('refunded', 'Remboursé'), ('failed', 'Échoué')], default='succeeded', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='agencies.agency')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
