# Generated by Django 5.2.11 on 2026-02-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('closed', 'Clôturé'), ('cancelled', 'Annulé')], default='draft', max_length=20),
        ),
    ]
