# Generated by Django 5.2.11 on 2026-02-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_contract_upgrade_signature_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='gps_clause',
            field=models.TextField(blank=True, default='', help_text='Clause GPS ajoutée au contrat si le véhicule est suivi'),
        ),
    ]
