# Generated by Django 5.0.14 on 2026-03-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_contract_gps_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('signed', 'Signed'), ('active', 'Actif'), ('pending_return', 'Retour en cours'), ('closed', 'Clôturé'), ('cancelled', 'Annulé')], default='draft', max_length=20),
        ),
    ]
