# Generated by Django 5.2.11 on 2026-02-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0008_agencyrole'),
        ('core', '0004_user_full_name_user_phone_user_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='agencies.agencyrole'),
        ),
    ]
