# Generated by Django 5.2.11 on 2026-02-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0009_permission_alter_agencyrole_unique_together_and_more'),
        ('core', '0005_user_agency_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agency_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='granted_permissions',
            field=models.ManyToManyField(blank=True, related_name='granted_to', to='agencies.permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='revoked_permissions',
            field=models.ManyToManyField(blank=True, related_name='revoked_from', to='agencies.permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_rank',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('accountant', 'Comptable'), ('secretary_tech', 'Secrétaire / Technicien'), ('technician', 'Technicien'), ('marketing', 'Marketing')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='use_custom_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
