# Generated by Django 5.2.11 on 2026-02-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_agency_role_remove_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, default='', max_length=255)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('subscription_id', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('agency_name', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'PayPal Event',
                'verbose_name_plural': 'PayPal Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('public_base_url', models.URLField(blank=True, default='', help_text='URL publique de la plateforme (ex: https://app.gaboomdriveos.com)')),
                ('paypal_mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10)),
                ('paypal_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('paypal_client_secret_encrypted', models.TextField(blank=True, default='', help_text='Chiffré via Fernet. Ne jamais stocker en clair.')),
                ('paypal_plan_id_sandbox', models.CharField(blank=True, default='', max_length=128)),
                ('paypal_plan_id_live', models.CharField(blank=True, default='', max_length=128)),
                ('paypal_webhook_id', models.CharField(blank=True, default='', help_text='Webhook ID PayPal pour la vérification de signature.', max_length=255)),
                ('paypal_webhook_verify', models.BooleanField(default=False, help_text='Activer la vérification de signature des webhooks PayPal.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
