# Generated by Django 5.2.11 on 2026-02-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paypalevent_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalevent',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paypalevent',
            name='resource_id',
            field=models.CharField(blank=True, default='', help_text='subscription_id or payment_id from the resource', max_length=120),
        ),
        migrations.AddField(
            model_name='paypalevent',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paypalevent',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
