# Generated by Django 5.2.11 on 2026-02-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0017_agencyaccess_paypal_fields'),
        ('core', '0008_paypalevent_note_paypalevent_resource_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='enable_paypal_auto',
            field=models.BooleanField(default=False, help_text='Activer le paiement PayPal automatique pour les agences.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='last_api_test_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='last_api_test_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='last_webhook_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_client_id_live',
            field=models.CharField(blank=True, default='', help_text='Client ID PayPal Live.', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_client_id_sandbox',
            field=models.CharField(blank=True, default='', help_text='Client ID PayPal Sandbox.', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_client_secret_live_encrypted',
            field=models.TextField(blank=True, default='', help_text='Client Secret Live chiffré via Fernet.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_client_secret_sandbox_encrypted',
            field=models.TextField(blank=True, default='', help_text='Client Secret Sandbox chiffré via Fernet.'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_product_id_live',
            field=models.CharField(blank=True, default='', help_text='Product ID PayPal Live (optionnel).', max_length=128),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_product_id_sandbox',
            field=models.CharField(blank=True, default='', help_text='Product ID PayPal Sandbox (optionnel).', max_length=128),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_webhook_id_live',
            field=models.CharField(blank=True, default='', help_text='Webhook ID PayPal Live.', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_webhook_id_sandbox',
            field=models.CharField(blank=True, default='', help_text='Webhook ID PayPal Sandbox.', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='subscription_currency',
            field=models.CharField(default='USD', help_text='Devise (USD, EUR, etc.).', max_length=3),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='subscription_price',
            field=models.DecimalField(decimal_places=2, default=29.99, help_text="Prix mensuel de l'abonnement.", max_digits=8),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='paypal_client_secret_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='paypal_webhook_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='AdminAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('paypal_cancelled', 'PayPal annulé'), ('paypal_failed', 'Paiement PayPal échoué'), ('paypal_suspended', 'PayPal suspendu'), ('paypal_expired', 'PayPal expiré'), ('mode_downgrade', 'Passage PayPal → Manuel'), ('mode_upgrade', 'Passage Manuel → PayPal'), ('manual_proof_pending', 'Preuve manuelle en attente'), ('unknown_event', 'Événement inconnu')], db_index=True, max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_alerts', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Admin Alert',
                'verbose_name_plural': 'Admin Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayPalSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_subscription_id', models.CharField(db_index=True, help_text='PayPal subscription ID (e.g. I-XXXXXXXXXX)', max_length=120, unique=True)),
                ('status', models.CharField(choices=[('APPROVAL_PENDING', "En attente d'approbation"), ('APPROVED', 'Approuvé'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu'), ('CANCELLED', 'Annulé'), ('EXPIRED', 'Expiré')], default='APPROVAL_PENDING', max_length=30)),
                ('plan_id', models.CharField(blank=True, default='', max_length=128)),
                ('product_id', models.CharField(blank=True, default='', max_length=128)),
                ('payer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('next_billing_time', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_sub', to='agencies.agencyaccess')),
            ],
            options={
                'verbose_name': 'PayPal Subscription',
                'verbose_name_plural': 'PayPal Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
