# Generated by Django 5.1.4 on 2026-02-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_platformsettings_enable_paypal_auto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agency_owner', 'Propriétaire'), ('agency_manager', 'Manager'), ('agency_secretary', 'Secrétaire'), ('agency_accountant', 'Comptable'), ('agency_staff', 'Employé'), ('read_only', 'Lecture seule')], default='agency_owner', help_text='Rôle RBAC officiel', max_length=30),
        ),
    ]
