# Generated by Django 5.1.4 on 2026-02-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_role_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff_rank',
        ),
    ]
