# Generated by Django 5.1.4 on 2026-02-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_access_level_remove_user_staff_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_plan_id_business_live',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_plan_id_business_sandbox',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_plan_id_enterprise_live',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_plan_id_enterprise_sandbox',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_plan_id_starter_live',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='paypal_plan_id_starter_sandbox',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
