# Generated by Django 5.1.4 on 2026-02-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_platformsettings_paypal_plan_id_business_live_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_api_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
