# Generated by Django 5.1.4 on 2026-02-11 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0031_remove_agency_billing_primary_and_more'),
        ('core', '0013_platformsettings_smtp_api_key_encrypted'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_password_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_provider',
            field=models.CharField(choices=[('brevo_api', 'Brevo API'), ('smtp', 'SMTP')], default='brevo_api', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_reply_to',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='smtp_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminalert',
            name='alert_type',
            field=models.CharField(choices=[('paypal_cancelled', 'PayPal annulé'), ('paypal_failed', 'Paiement PayPal échoué'), ('paypal_suspended', 'PayPal suspendu'), ('paypal_expired', 'PayPal expiré'), ('mode_downgrade', 'Passage PayPal → Manuel'), ('mode_upgrade', 'Passage Manuel → PayPal'), ('manual_proof_pending', 'Preuve manuelle en attente'), ('unknown_event', 'Événement inconnu'), ('email_failed', 'Email échoué')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='EmailSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(blank=True, default='', max_length=80)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
