# Generated by Django 5.0.14 on 2026-03-17 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0033_agency_marketing_email_api_key_encrypted_and_more'),
        ('core', '0014_emailtemplate_platformsettings_smtp_from_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(help_text="Type de pattern (ex: 'browser_lang', 'time_based', 'geo_based')", max_length=50)),
                ('pattern_data', models.JSONField(help_text='Données du pattern')),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pattern linguistique',
                'verbose_name_plural': 'Patterns linguistiques',
                'ordering': ['-confidence_score', '-success_count'],
            },
        ),
        migrations.CreateModel(
            name='UserLanguagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('ht', 'Kreyòl')], max_length=5)),
                ('source', models.CharField(choices=[('browser', 'Navigateur'), ('session', 'Session'), ('manual', 'Manuel'), ('detected', 'Détecté automatiquement')], default='detected', max_length=20)),
                ('confidence', models.FloatField(default=1.0, help_text='Niveau de confiance de 0 à 1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_preferences', to='agencies.agency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence linguistique',
                'verbose_name_plural': 'Préférences linguistiques',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_userla_user_id_f0d946_idx'), models.Index(fields=['agency', '-created_at'], name='core_userla_agency__bb1d66_idx'), models.Index(fields=['session_key', '-created_at'], name='core_userla_session_d8ad1d_idx'), models.Index(fields=['ip_address', '-created_at'], name='core_userla_ip_addr_beb377_idx'), models.Index(fields=['language', '-created_at'], name='core_userla_languag_2fb9a7_idx')],
            },
        ),
    ]
