# Generated by Django 5.0.14 on 2026-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_language_preference_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='master_code_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
