# Generated by Django 5.1.4 on 2026-02-09 19:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0023_marketingcampaign_channel_config_campaignautomation_and_more'),
        ('clients', '0005_clientloyalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=80)),
                ('name', models.CharField(default='', max_length=120)),
                ('objective', models.CharField(choices=[('promo', 'Promotion'), ('relance', 'Relance'), ('fidelisation', 'Fidélisation'), ('avis', 'Avis client'), ('lancement', 'Lancement')], default='promo', max_length=20)),
                ('style', models.CharField(choices=[('simple', 'Simple'), ('corporate', 'Corporate'), ('urgent', 'Urgent'), ('luxe', 'Luxe'), ('ultra_premium', 'Ultra Premium')], default='simple', max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=10)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('content', models.TextField(default='')),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mkt_templates', to='agencies.agency')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='MktCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('objective', models.CharField(choices=[('promo', 'Promotion'), ('relance', 'Relance'), ('fidelisation', 'Fidélisation'), ('avis', 'Avis client'), ('lancement', 'Lancement')], default='promo', max_length=20)),
                ('channel_email', models.BooleanField(default=True)),
                ('channel_whatsapp', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifiée'), ('running', 'En cours'), ('done', 'Terminée')], default='draft', max_length=20)),
                ('target', models.CharField(choices=[('all_clients', 'Tous les clients'), ('active_clients', 'Clients actifs'), ('inactive_30d', 'Inactifs 30 jours'), ('custom_tag', 'Tag personnalisé')], default='all_clients', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('ab_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_campaigns', to='agencies.agency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(default='A', max_length=5)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('body_text', models.TextField(default='')),
                ('style', models.CharField(choices=[('simple', 'Simple'), ('corporate', 'Corporate'), ('urgent', 'Urgent'), ('luxe', 'Luxe'), ('ultra_premium', 'Ultra Premium')], default='simple', max_length=20)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='marketing.mktcampaign')),
            ],
            options={
                'ordering': ['variant'],
                'unique_together': {('campaign', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='CampaignSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=10)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mkt_sends', to='clients.clientaccount')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sends', to='marketing.campaignvariant')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='marketing.mktcampaign')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('wa_link', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'À envoyer'), ('sent', 'Envoyé')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_outbox', to='agencies.agency')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_outbox', to='marketing.mktcampaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_outbox', to='clients.clientaccount')),
            ],
            options={
                'verbose_name': 'WhatsApp Outbox',
                'verbose_name_plural': 'WhatsApp Outbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('reservation_pending_followup', 'Relance réservation en attente'), ('booking_confirmed', 'Confirmation réservation'), ('pre_start_reminder', 'Rappel 24h avant location'), ('post_end_review', 'Demande avis après location'), ('inactive_30d_offer', 'Offre client inactif 30j')], max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Email + WhatsApp')], default='email', max_length=10)),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('delay_days', models.PositiveSmallIntegerField(default=0)),
                ('template_key', models.CharField(blank=True, default='', max_length=80)),
                ('custom_content', models.TextField(blank=True, default='')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='agencies.agency')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('agency', 'key')},
            },
        ),
        migrations.CreateModel(
            name='BanditArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_key', models.CharField(db_index=True, max_length=120)),
                ('pulls', models.PositiveIntegerField(default=0)),
                ('rewards', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandit_arms', to='agencies.agency')),
            ],
            options={
                'ordering': ['-rewards'],
                'unique_together': {('agency', 'arm_key')},
            },
        ),
    ]
