# Generated by Django 5.1.4 on 2026-02-09 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationrule',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='automationrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='dry_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules', to='marketing.marketingtemplate'),
        ),
    ]
