# Generated by Django 5.1.4 on 2026-02-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_automationrule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappoutbox',
            name='status',
            field=models.CharField(choices=[('pending', 'À envoyer'), ('sent', 'Envoyé'), ('failed', 'Échoué')], default='pending', max_length=10),
        ),
    ]
