# Generated by Django 5.2.11 on 2026-02-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0018_reservationrequest_client_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
                ('show_in_nav', models.BooleanField(default=False)),
                ('nav_order', models.PositiveIntegerField(default=0)),
                ('template_variant', models.CharField(choices=[('default', 'Par défaut'), ('hero', 'Hero / Landing'), ('faq', 'FAQ'), ('contact', 'Contact'), ('legal', 'Mentions légales')], default='default', max_length=20)),
                ('seo_title', models.CharField(blank=True, default='', max_length=200)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_pages', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Page publique',
                'verbose_name_plural': 'Pages publiques',
                'ordering': ['nav_order', 'title'],
                'unique_together': {('agency', 'slug')},
            },
        ),
    ]
