# Generated by Django 5.2.11 on 2026-02-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpage',
            name='cta_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='publicpage',
            name='cta_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='publicpage',
            name='template_variant',
            field=models.CharField(choices=[('default', 'Par défaut'), ('about', 'À propos'), ('faq', 'FAQ'), ('contact', 'Contact'), ('legal', 'Mentions légales'), ('promo', 'Promo / Landing')], default='default', max_length=20),
        ),
    ]
