# Generated by Django 5.2.11 on 2026-02-07 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_agency_currency_agency_fuel_fee_default_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('vip', 'VIP'), ('blacklisted', 'Blacklisté')], default='active', max_length=20)),
                ('follow_up_at', models.DateField(blank=True, null=True)),
                ('follow_up_note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='agencies.agency')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.DeleteModel(
            name='ClientUser',
        ),
    ]
