# Generated by Django 5.2.11 on 2026-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_delete_clientuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='driving_license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='driving_license_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='clients/id/'),
        ),
    ]
