# Generated by Django 5.0.14 on 2026-03-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0033_agency_marketing_email_api_key_encrypted_and_more'),
        ('clients', '0006_negotiationmessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientaccount',
            unique_together={('agency', 'full_name')},
        ),
    ]
