# Generated by Django 5.0.14 on 2026-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0033_agency_marketing_email_api_key_encrypted_and_more'),
        ('clients', '0007_change_unique_together_full_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='clientaccount',
            unique_together={('agency', 'username')},
        ),
    ]
