# Generated by Django 5.0.14 on 2026-03-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_populate_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaccount',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
