# Generated by Django 5.2.11 on 2026-02-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ACCESS_RENEW', 'Renouvellement accès'), ('ACCESS_SUSPEND', 'Suspension accès'), ('ACCESS_BONUS', 'Bonus jours'), ('PROOF_APPROVE', 'Preuve approuvée'), ('PROOF_REJECT', 'Preuve rejetée'), ('NOTES_UPDATE', 'Notes mises à jour'), ('SETTINGS_UPDATE', 'Paramètres modifiés'), ('ALERT_DISMISS', 'Alerte traitée'), ('PAYPAL_SWITCH', 'Changement mode paiement')], max_length=30),
        ),
    ]
