# Generated by Django 5.2.11 on 2026-02-06 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('public_enabled', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_enabled', models.BooleanField(default=False)),
                ('subscription_status', models.CharField(default='trial', max_length=50)),
                ('primary_color', models.CharField(default='#6D28D9', max_length=20)),
                ('secondary_color', models.CharField(default='#FACC15', max_length=20)),
                ('theme', models.CharField(default='default', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=50)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='available', max_length=20)),
                ('public_visible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
            ],
            options={
                'ordering': ['make', 'model', 'plate_number'],
            },
        ),
    ]
