# Generated by Django 5.2.11 on 2026-02-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_public_city_agency_public_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='slug',
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
