# Generated by Django 5.2.11 on 2026-02-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_alter_agency_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
