# Generated by Django 5.2.11 on 2026-02-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_agency_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='currency',
            field=models.CharField(default='EUR', max_length=5),
        ),
        migrations.AddField(
            model_name='agency',
            name='fuel_fee_default',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='agency',
            name='km_included_default',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='agency',
            name='km_price_default',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=6),
        ),
        migrations.AddField(
            model_name='agency',
            name='late_fee_default',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='agency',
            name='maintenance_interval_km',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='agency',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_maintenance_km',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
