# Generated by Django 5.2.11 on 2026-02-07 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_agency_address_line1_agency_address_line2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='agencies.agency')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('agency', 'name')},
            },
        ),
    ]
