# Generated by Django 5.2.11 on 2026-02-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0008_agencyrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('group', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='agencyrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='agencyrole',
            name='agency',
        ),
    ]
