# Generated by Django 5.2.11 on 2026-02-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0009_permission_alter_agencyrole_unique_together_and_more'),
        ('core', '0006_remove_user_agency_role_remove_user_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgencyRole',
        ),
    ]
