# Generated by Django 5.2.11 on 2026-02-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0010_delete_agencyrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_included', models.PositiveIntegerField(blank=True, default=200, null=True)),
                ('km_type', models.CharField(blank=True, choices=[('per_day', 'Par jour'), ('per_contract', 'Par contrat')], default='per_day', max_length=20)),
                ('km_unlimited', models.BooleanField(default=False)),
                ('km_extra_price', models.DecimalField(blank=True, decimal_places=2, default=0.3, max_digits=8, null=True)),
                ('late_tolerance_minutes', models.PositiveIntegerField(blank=True, default=30, null=True)),
                ('late_billing_mode', models.CharField(blank=True, choices=[('prorata', 'Prorata'), ('full_day', 'Journée entière')], default='prorata', max_length=20)),
                ('late_fee_per_day', models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=8, null=True)),
                ('fuel_policy', models.CharField(blank=True, choices=[('full_full', 'Plein → Plein'), ('full_empty', 'Plein → Vide'), ('free', 'Libre')], default='full_full', max_length=20)),
                ('fuel_fee', models.DecimalField(blank=True, decimal_places=2, default=30.0, max_digits=8, null=True)),
                ('vat_percent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('currency', models.CharField(blank=True, choices=[('EUR', 'EUR — Euro'), ('USD', 'USD — Dollar US'), ('MAD', 'MAD — Dirham'), ('XOF', 'XOF — Franc CFA'), ('GBP', 'GBP — Livre sterling'), ('CAD', 'CAD — Dollar canadien'), ('CHF', 'CHF — Franc suisse'), ('TND', 'TND — Dinar tunisien'), ('DZD', 'DZD — Dinar algérien')], default='EUR', max_length=5)),
                ('invoice_rounding', models.CharField(blank=True, choices=[('0.01', '0.01'), ('0.05', '0.05'), ('1', '1')], default='0.01', max_length=5)),
                ('deposit_default', models.DecimalField(blank=True, decimal_places=2, default=500.0, max_digits=10, null=True)),
                ('deposit_mode', models.CharField(blank=True, choices=[('card_hold', 'Empreinte carte'), ('cash', 'Espèce'), ('transfer', 'Virement')], default='cash', max_length=20)),
                ('insurance_franchise', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('insurance_included', models.BooleanField(default=False)),
                ('franchise_buyback', models.BooleanField(default=False)),
                ('franchise_buyback_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('auto_number_contracts', models.BooleanField(default=True)),
                ('auto_number_invoices', models.BooleanField(default=True)),
                ('contract_prefix', models.CharField(blank=True, default='CTR-', max_length=20)),
                ('invoice_prefix', models.CharField(blank=True, default='FAC-', max_length=20)),
                ('pay_cash', models.BooleanField(default=True)),
                ('pay_card', models.BooleanField(default=True)),
                ('pay_transfer', models.BooleanField(default=False)),
                ('pay_mobile_money', models.BooleanField(default=False)),
                ('partial_payment_allowed', models.BooleanField(default=False)),
                ('invoice_due_days', models.PositiveIntegerField(blank=True, default=30, null=True)),
                ('maintenance_interval_km', models.PositiveIntegerField(blank=True, default=10000, null=True)),
                ('maintenance_interval_months', models.PositiveIntegerField(blank=True, default=6, null=True)),
                ('maintenance_alert_km', models.PositiveIntegerField(blank=True, default=500, null=True)),
                ('maintenance_alert_days', models.PositiveIntegerField(blank=True, default=15, null=True)),
                ('maintenance_email_alert', models.BooleanField(default=False)),
                ('maintenance_disable_vehicle', models.BooleanField(default=False)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_settings', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
            },
        ),
    ]
