# Generated by Django 5.2.11 on 2026-02-07 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0011_businesssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('km_at_service', models.PositiveIntegerField()),
                ('service_type', models.CharField(choices=[('oil_change', 'Vidange'), ('tires', 'Pneus'), ('revision', 'Révision générale'), ('brakes', 'Freins'), ('battery', 'Batterie'), ('filters', 'Filtres'), ('timing_belt', 'Courroie de distribution'), ('other', 'Autre')], default='revision', max_length=30)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='agencies.vehicle')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
