# Generated by Django 5.2.11 on 2026-02-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0012_vehicle_last_maintenance_date_maintenancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='maintenance_grace_km',
            field=models.PositiveIntegerField(blank=True, default=300, null=True),
        ),
    ]
