# Generated by Django 5.2.11 on 2026-02-07 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0013_businesssettings_maintenance_grace_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencySiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=20)),
                ('is_public_enabled', models.BooleanField(default=True)),
                ('is_maintenance_enabled', models.BooleanField(default=False)),
                ('theme_key', models.CharField(default='default', max_length=64)),
                ('primary_color', models.CharField(default='#6D28D9', max_length=16)),
                ('secondary_color', models.CharField(default='#FACC15', max_length=16)),
                ('font_family', models.CharField(default='Inter', max_length=64)),
                ('hero_title', models.CharField(blank=True, default='', max_length=120)),
                ('hero_subtitle', models.CharField(blank=True, default='', max_length=180)),
                ('cta_text', models.CharField(blank=True, default='Réserver', max_length=60)),
                ('city', models.CharField(blank=True, default='', max_length=80)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agencies/site_logos/')),
                ('seo_title', models.CharField(blank=True, default='', max_length=70)),
                ('seo_description', models.CharField(blank=True, default='', max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Agency Site Settings',
                'verbose_name_plural': 'Agency Site Settings',
            },
        ),
        migrations.CreateModel(
            name='AgencySiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home')], default='home', max_length=32)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(default='', max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=160)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_json', models.JSONField(blank=True, default=dict)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_sections', to='agencies.agency')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('agency', 'page', 'key'), name='uniq_agency_page_key')],
            },
        ),
    ]
