# Generated by Django 5.2.11 on 2026-02-07 18:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0014_agencysitesettings_agencysitesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('rejected', 'Refusée'), ('expired', 'Expirée')], default='pending', max_length=20)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('message', models.TextField(blank=True, default='')),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('public_secret', models.CharField(default='', editable=False, max_length=64)),
                ('client_seen_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('decision_message', models.CharField(blank=True, default='', max_length=180)),
                ('desired_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('source', models.CharField(choices=[('public_site', 'Site public'), ('dashboard', 'Dashboard'), ('phone', 'Téléphone')], default='public_site', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='agencies.agency')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='agencies.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agency', 'status', 'created_at'], name='agencies_re_agency__52ff74_idx'), models.Index(fields=['vehicle', 'start_date', 'end_date'], name='agencies_re_vehicle_a4a5af_idx'), models.Index(fields=['public_token'], name='agencies_re_public__6365be_idx')],
            },
        ),
    ]
