# Generated by Django 5.2.11 on 2026-02-08 12:21

import agencies.models_access
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0015_reservationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Essai gratuit'), ('active', 'Actif'), ('suspended', 'Suspendu')], default='trial', max_length=20)),
                ('trial_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('access_ends_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date limite actuelle (fin trial ou fin active).')),
                ('suspended_reason', models.TextField(blank=True, default='')),
                ('notes_internal', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Agency Access',
                'verbose_name_plural': 'Agency Accesses',
            },
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='payments/proofs/%Y/%m/', validators=[agencies.models_access._validate_proof_image])),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, default='')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='agencies.agencyaccess')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proofs', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
