# Generated by Django 5.2.11 on 2026-02-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0016_agencyaccess_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyaccess',
            name='admin_alert_code',
            field=models.CharField(choices=[('none', 'Aucune'), ('paypal_cancelled', 'PayPal annulé'), ('paypal_payment_failed', 'Paiement PayPal échoué'), ('paypal_status_unknown', 'Statut PayPal inconnu'), ('paypal_to_manual', 'PayPal → Manuel'), ('manual_to_paypal', 'Manuel → PayPal')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='admin_alert_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='billing_last_changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='billing_last_changed_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='billing_mode',
            field=models.CharField(choices=[('manual', 'Manuel'), ('paypal', 'PayPal')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='needs_admin_attention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='paypal_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='paypal_last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='paypal_status',
            field=models.CharField(choices=[('none', 'Aucun'), ('active', 'Actif'), ('cancelled', 'Annulé'), ('suspended', 'Suspendu'), ('expired', 'Expiré')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='paypal_subscription_id',
            field=models.CharField(blank=True, default='', help_text="ID d'abonnement PayPal (ex: I-XXXXXXXXXX).", max_length=120),
        ),
    ]
