# Generated by Django 5.2.11 on 2026-02-09 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0017_agencyaccess_paypal_fields'),
        ('clients', '0004_clientaccount_clientnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationrequest',
            name='client_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='clients.clientaccount'),
        ),
    ]
