# Generated by Django 5.2.11 on 2026-02-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0018_reservationrequest_client_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='allow_price_negotiation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='negotiation_min_percent',
            field=models.PositiveSmallIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='agency_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='daily_price_accepted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='daily_price_counter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='daily_price_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='daily_price_official',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='negotiation_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reservationrequest',
            name='negotiation_status',
            field=models.CharField(choices=[('none', 'Standard'), ('pending_offer', 'Offre client'), ('countered', 'Contre-offre'), ('accepted', 'Accord'), ('refused', 'Refusé')], default='none', max_length=20),
        ),
    ]
