# Generated by Django 5.2.11 on 2026-02-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0019_businesssettings_allow_price_negotiation_and_more'),
        ('clients', '0005_clientloyalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_choice', models.CharField(choices=[('dark', 'Dark Luxury'), ('clear', 'Clear Pro'), ('gaboom', 'Gaboom Signature')], default='gaboom', max_length=20)),
                ('primary_color', models.CharField(blank=True, default='', max_length=20)),
                ('secondary_color', models.CharField(blank=True, default='', max_length=20)),
                ('border_radius', models.PositiveSmallIntegerField(default=14)),
                ('enable_animations', models.BooleanField(default=True)),
                ('enable_glow_effect', models.BooleanField(default=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_settings', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target_type', models.CharField(choices=[('all', 'Tous les clients'), ('inactive', 'Clients inactifs'), ('frequent', 'Clients fréquents'), ('negotiators', 'Négociateurs')], default='all', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifiée'), ('sent', 'Envoyée')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='agencies.agency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('failed', 'Échoué')], default='sent', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_logs', to='clients.clientaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agencies.marketingcampaign')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hero', 'Hero'), ('inline', 'Inline'), ('popup', 'Popup'), ('sidebar', 'Sidebar'), ('countdown', 'Countdown')], default='hero', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('button_text', models.CharField(blank=True, default='', max_length=60)),
                ('button_link', models.CharField(blank=True, default='', max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_device', models.CharField(choices=[('all', 'Tous'), ('mobile', 'Mobile'), ('desktop', 'Desktop')], default='all', max_length=10)),
                ('animation_type', models.CharField(choices=[('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom')], default='fade', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_banners', to='agencies.agency')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('percent', 'Pourcentage'), ('fixed', 'Montant fixe')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('max_usage', models.PositiveIntegerField(default=0)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='agencies.agency')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('agency', 'code')},
            },
        ),
    ]
