# Generated by Django 5.2.11 on 2026-02-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0020_agencythemesettings_marketingcampaign_campaignlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencythemesettings',
            name='theme_choice',
            field=models.CharField(choices=[('dark', 'Dark Luxury'), ('light', 'Light Pro'), ('clear', 'Clear Pro'), ('gaboom', 'Gaboom Signature')], default='gaboom', max_length=20),
        ),
    ]
