# Generated by Django 5.2.11 on 2026-02-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0021_add_light_theme_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencythemesettings',
            name='theme_choice',
            field=models.CharField(choices=[('dark', 'Dark Luxury'), ('gaboom', 'Gaboom Signature')], default='dark', max_length=20),
        ),
    ]
