# Generated by Django 5.2.11 on 2026-02-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0022_simplify_theme_choices'),
        ('clients', '0005_clientloyalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='channel_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CampaignAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('is_sequence', models.BooleanField(default=False)),
                ('trigger', models.CharField(choices=[('manual', 'Manuel (ponctuel)'), ('new_client', 'Nouveau client'), ('pending_reservation', 'Réservation en attente'), ('contract_ended', 'Contrat terminé'), ('inactive_client', 'Client inactif')], default='manual', max_length=30)),
                ('stop_conditions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation', to='agencies.marketingcampaign')),
            ],
            options={
                'verbose_name': 'Campaign Automation',
            },
        ),
        migrations.CreateModel(
            name='CampaignStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('day_offset', models.PositiveSmallIntegerField(default=0)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='email', max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('send_time', models.TimeField(default='09:00')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agencies.campaignautomation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='email', max_length=10)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'En file'), ('sent', 'Envoyé'), ('failed', 'Échoué')], default='queued', max_length=10)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('wa_link', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='agencies.marketingcampaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='clients.clientaccount')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_messages', to='agencies.campaignstep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
