# Generated by Django 5.2.11 on 2026-02-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0025_businesssettings_contract_clauses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('contracted', 'Sous contrat'), ('rejected', 'Refusée'), ('expired', 'Expirée')], default='pending', max_length=20),
        ),
    ]
