# Generated by Django 5.2.11 on 2026-02-10 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0026_reservation_contracted_status'),
        ('billing', '0004_contract_gps_clause'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='default_gps_clause',
            field=models.TextField(blank=True, default="Le véhicule est équipé d'un système de géolocalisation GPS. Le locataire est informé que la position du véhicule peut être suivie pendant toute la durée du contrat à des fins de sécurité et de gestion de flotte. Le locataire s'engage à ne pas désactiver, endommager ou interférer avec le dispositif GPS. Toute entrée dans une zone géographique interdite définie par l'agence déclenchera une alerte et pourra entraîner des pénalités."),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='gps_offline_alert_minutes',
            field=models.PositiveIntegerField(blank=True, default=30, help_text='Alerte si GPS hors ligne (minutes)', null=True),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='gps_speed_limit',
            field=models.PositiveIntegerField(blank=True, default=130, help_text='Limite de vitesse (km/h)', null=True),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='gps_tracking_enabled',
            field=models.BooleanField(default=False, help_text="Activer le suivi GPS pour l'agence"),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_enabled',
            field=models.BooleanField(default=False, help_text='Suivi GPS activé'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_imei',
            field=models.CharField(blank=True, default='', help_text='IMEI du boîtier GPS', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP du tracker GPS', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gps_source',
            field=models.CharField(blank=True, choices=[('device', 'Boîtier GPS'), ('phone', 'Téléphone client')], default='device', help_text='Source du signal GPS', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_gps_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_gps_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='GeoZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('zone_type', models.CharField(choices=[('restricted', 'Zone interdite'), ('allowed', 'Zone autorisée')], default='restricted', max_length=20)),
                ('center_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('center_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('radius_km', models.DecimalField(decimal_places=2, default=5, help_text='Rayon en km', max_digits=7)),
                ('polygon_json', models.TextField(blank=True, default='', help_text='GeoJSON coordinates (optional)')),
                ('alert_enabled', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, default='#ef4444', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_zones', to='agencies.agency')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GPSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('zone_enter', 'Entrée zone interdite'), ('zone_exit', 'Sortie zone autorisée'), ('speed', 'Excès de vitesse'), ('offline', 'GPS hors ligne')], max_length=20)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_alerts', to='agencies.agency')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_alerts', to='billing.contract')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_alerts', to='agencies.vehicle')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='agencies.geozone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GPSPositionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('source', models.CharField(default='device', max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to='agencies.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['vehicle', '-recorded_at'], name='agencies_gp_vehicle_6a7405_idx')],
            },
        ),
    ]
