# Generated by Django 5.1.4 on 2026-02-10 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0027_businesssettings_default_gps_clause_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='stripe_enabled',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='stripe_subscription_id',
        ),
    ]
