# Generated by Django 5.1.4 on 2026-02-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0028_remove_agency_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyaccess',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter (59$/mois)'), ('pro', 'Pro (99$/mois)'), ('enterprise', 'Enterprise (199$/mois)')], default='starter', help_text='Plan tarifaire choisi (détermine les limites et fonctionnalités).', max_length=20),
        ),
        migrations.AlterField(
            model_name='agencyaccess',
            name='status',
            field=models.CharField(choices=[('trial', 'Essai gratuit'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('expired', 'Expiré')], default='trial', max_length=20),
        ),
    ]
