# Generated by Django 5.1.4 on 2026-02-11 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0029_agencyaccess_plan_alter_agencyaccess_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='billing_primary',
            field=models.ForeignKey(blank=True, help_text='Agence primaire de facturation (si vide: cette agence est la primaire).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_children', to='agencies.agency'),
        ),
        migrations.AlterField(
            model_name='agencyaccess',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter (59$/mois)'), ('business', 'Business (99$/mois)'), ('enterprise', 'Enterprise (199$/mois)'), ('pro', 'Pro (99$/mois)')], default='starter', help_text='Plan tarifaire choisi (détermine les limites et fonctionnalités).', max_length=20),
        ),
    ]
