# Generated by Django 5.1.4 on 2026-02-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0030_agency_billing_primary_alter_agencyaccess_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='billing_primary',
        ),
        migrations.RemoveField(
            model_name='agencyaccess',
            name='plan',
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='max_agencies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='max_users',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='max_vehicles',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='plan_code',
            field=models.CharField(choices=[('starter', 'Starter'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='plan_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='plan_features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='plan_name',
            field=models.CharField(default='Starter', max_length=40),
        ),
        migrations.AddField(
            model_name='agencyaccess',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, default=59, max_digits=8),
        ),
        migrations.AlterField(
            model_name='agencyaccess',
            name='status',
            field=models.CharField(choices=[('trial', 'Essai gratuit'), ('active', 'Actif'), ('suspended', 'Suspendu')], default='trial', max_length=20),
        ),
    ]
