# Generated by Django 5.1.4 on 2026-02-12 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0031_remove_agency_billing_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geozone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gpsalert',
            name='alert_type',
            field=models.CharField(choices=[('zone_enter', 'Entrée zone interdite'), ('zone_exit', 'Sortie zone autorisée'), ('zone_violation', 'Violation zone interdite'), ('speed', 'Excès de vitesse'), ('offline', 'GPS hors ligne')], max_length=20),
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enter', 'Entrée'), ('exit', 'Sortie'), ('violation', 'Violation')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='agencies.agency')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='agencies.vehicle')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agencies.geozone')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='GPSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('generic', 'Generic'), ('brand_x', 'Brand X')], default='generic', max_length=30)),
                ('imei', models.CharField(max_length=50)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('auth_token', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_devices', to='agencies.agency')),
                ('linked_vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gps_device', to='agencies.vehicle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agency', 'imei'), name='gps_device_unique_imei_agency')],
            },
        ),
        migrations.CreateModel(
            name='VehicleZoneState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inside', models.BooleanField(default=False)),
                ('last_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_violation_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_zone_states', to='agencies.agency')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_states', to='agencies.vehicle')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_states', to='agencies.geozone')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'zone'), name='vehicle_zone_state_unique')],
            },
        ),
    ]
