# Generated by Django 5.1.4 on 2026-02-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0032_geozone_is_active_alter_gpsalert_alert_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='marketing_email_api_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agency',
            name='marketing_email_from',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='agency',
            name='marketing_whatsapp_api_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agency',
            name='marketing_whatsapp_phone_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='campaignstep',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
        migrations.AlterField(
            model_name='outboundmessage',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=10),
        ),
    ]
