# Generated by Django 5.0.14 on 2026-03-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0033_agency_marketing_email_api_key_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='agency_signature',
            field=models.ImageField(blank=True, null=True, upload_to='agencies/signatures/'),
        ),
    ]
