# Generated by Django 5.0.14 on 2026-03-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0034_agency_agency_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('ht', 'Kreyòl')], default='fr', max_length=5),
        ),
    ]
