THEMES = [
    {
        "id": "default",
        "name": "Default Premium",
        "primary": "#6D28D9",
        "secondary": "#FACC15",
        "bg": "#ffffff",
        "card_bg": "#f8fafc",
        "text": "#0f172a",
        "style": "soft",
    },
    {
        "id": "dark_neon",
        "name": "Dark Neon",
        "primary": "#8B5CF6",
        "secondary": "#22D3EE",
        "bg": "#0f172a",
        "card_bg": "#1e293b",
        "text": "#f1f5f9",
        "style": "dark",
    },
    {
        "id": "black_gold",
        "name": "Black & Gold",
        "primary": "#D4A017",
        "secondary": "#F5E6B8",
        "bg": "#111111",
        "card_bg": "#1a1a1a",
        "text": "#f5f5f5",
        "style": "dark",
    },
    {
        "id": "emerald_pro",
        "name": "Emerald Pro",
        "primary": "#059669",
        "secondary": "#A7F3D0",
        "bg": "#ffffff",
        "card_bg": "#f0fdf4",
        "text": "#0f172a",
        "style": "soft",
    },
    {
        "id": "classic_blue",
        "name": "Classic Blue",
        "primary": "#2563EB",
        "secondary": "#93C5FD",
        "bg": "#ffffff",
        "card_bg": "#eff6ff",
        "text": "#0f172a",
        "style": "soft",
    },
    {
        "id": "sunset",
        "name": "Sunset",
        "primary": "#EA580C",
        "secondary": "#FDE68A",
        "bg": "#fffbeb",
        "card_bg": "#fff7ed",
        "text": "#1c1917",
        "style": "warm",
    },
    {
        "id": "soft_pastel",
        "name": "Soft Pastel",
        "primary": "#A78BFA",
        "secondary": "#FCA5A5",
        "bg": "#faf5ff",
        "card_bg": "#ffffff",
        "text": "#1e1b4b",
        "style": "soft",
    },
    {
        "id": "corporate_gray",
        "name": "Corporate Gray",
        "primary": "#475569",
        "secondary": "#94A3B8",
        "bg": "#ffffff",
        "card_bg": "#f1f5f9",
        "text": "#0f172a",
        "style": "corporate",
    },
    {
        "id": "beige_luxe",
        "name": "Beige Luxe",
        "primary": "#92400E",
        "secondary": "#D6C4A8",
        "bg": "#FAF7F2",
        "card_bg": "#ffffff",
        "text": "#1c1917",
        "style": "warm",
    },
    {
        "id": "tropical",
        "name": "Tropical",
        "primary": "#0D9488",
        "secondary": "#FCD34D",
        "bg": "#ffffff",
        "card_bg": "#f0fdfa",
        "text": "#0f172a",
        "style": "soft",
    },
    {
        "id": "night_runner",
        "name": "Night Runner",
        "primary": "#E11D48",
        "secondary": "#818CF8",
        "bg": "#0f0f1a",
        "card_bg": "#1a1a2e",
        "text": "#e2e8f0",
        "style": "dark",
    },
    {
        "id": "minimal_white",
        "name": "Minimal White",
        "primary": "#18181B",
        "secondary": "#E4E4E7",
        "bg": "#ffffff",
        "card_bg": "#fafafa",
        "text": "#18181b",
        "style": "minimal",
    },
]

THEMES_BY_ID = {t["id"]: t for t in THEMES}
